version: '3'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:11
    restart: always
    volumes:
      - ./sql:/sql
    environment:
      POSTGRES_USER: super_user
      POSTGRES_PASSWORD: super_password
    ports:
      - 5432:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
